; SEGMENT A START — Project Environment
[env:m5stack-stamps3]
platform = espressif32
board = m5stack-stamps3
framework = arduino

board_build.flash_size = 8MB

build_flags =
  -Os
  -DCORE_DEBUG_LEVEL=0

lib_deps =
  m5stack/M5Cardputer@^1.0.3
  fastled/FastLED@^3.3.3
  https://github.com/T-vK/ESP32-BLE-Keyboard.git#0.2.3
; SEGMENT A END — Project Environment